source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

# Rails core
gem 'rails', '~> 5.1.0.rc1'

# Rails Application Server
gem 'puma', '~> 3.7'

<% if api? -%>
# API Infrastructure
gem 'jsonapi-authorization', '~> 1.0.0.alpha2'
gem 'jsonapi-resources', github: 'cerebris/jsonapi-resources'
gem 'jwt'
gem 'rack-cors'
<% else -%>
# UI Foundation
gem 'coffee-rails', '~> 4.2'
gem 'sass-rails', github: 'rails/sass-rails'
gem 'simple_form'
gem 'slim-rails'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'

# UI Gems
gem 'bootstrap', '~> 4.0.0.alpha6'
gem 'font-awesome-sass'
gem 'jquery-rails'
gem 'russian'
gem 'unobtrusive_flash'

source 'https://rails-assets.org' do
  gem 'rails-assets-tether', '>= 1.3.3'
  gem 'rails-assets-toastr'
end
<% end -%>

# Common Business Logic
gem 'pundit'

<% unless api? -%>
# UI Business Logic
gem 'devise'
gem 'draper', github: 'drapergem/draper'
<% end -%>

# Temporary Thor override
gem 'thor', github: 'erikhuda/thor'

group :development, :test do
  gem 'awesome_print'
  gem 'better_errors'
  gem 'byebug', platform: :mri
  gem 'factory_girl_rails'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 3.5.0'

  gem 'sqlite3'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
end

group :test do
  gem 'database_cleaner', github: 'DatabaseCleaner/database_cleaner'
  gem 'faker'
  gem 'pundit-matchers'
  gem 'rspec_junit_formatter'
  gem 'shoulda-matchers', '~> 3.1'

  # API Testing
  gem 'jsonapi-resources-matchers'
end

group :production do
  gem 'pg', '~> 0.19'

  gem 'logstasher'
end

# Windows does not include zone info files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :jruby]
